#' Add a create slide request
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param insertion_index A numeric vector on where the slide is to be added
#' @param layout_id A character vector that provides guidance on which layout the new slide is to follow
#' @param predefined_layout A character vector that provides guidance on which layout the new slide
#' is to follow. The ones declared here
#' @param object_id A character vector that is to be used to give names to new slides created via the
#' slides API
#' @export
add_create_slide_page_request <- function(google_slides_request = NULL, insertion_index=NULL,
                               layout_id=NULL, predefined_layout=NULL,
                               object_id=NULL){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }

  create_slide_request <- list(createSlide=list(slideLayoutReference=list()))

  # Define object id as slide reference
  if(!is.null(object_id)){
    create_slide_request[["createSlide"]][["objectId"]] <- object_id
  }

  # Define insertion index on where the slides to be appended
  if(!is.null(insertion_index)){
    create_slide_request[["createSlide"]][["insertionIndex"]] <- insertion_index
  }

  # If layout id is available, use layout id, else use predefinedLayout or else if uses default blank layout
  if(!is.null(layout_id)){
    create_slide_request[["createSlide"]][["slideLayoutReference"]][["layoutId"]] <- layout_id
  } else if(!is.null(predefined_layout)){
    create_slide_request[["createSlide"]][["slideLayoutReference"]][["predefinedLayout"]] <- predefined_layout
  } else {
    create_slide_request[["createSlide"]][["slideLayoutReference"]][["predefinedLayout"]] <- "BLANK"
  }

  google_slides_request$add_request(create_slide_request)
  return(google_slides_request)
}


#' Add a create shape request
#' @description This function builds up the request for creating shapes within Googleslides via the API.
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param shape_type A character vector that contains the shape type for the new shape that is to be created
#' @param page_element_property A list that contains a page element property. The page element is to be
#' generated by the page_element_property function in this package. IT IS COMPULSORY TO ADD WIDTH AND HEIGHT AS
#' PART OF THE page_element_property
#' @param object_id (Optional) A character vector to name the object created instead of leaving it to Google
#' @export
add_create_shape_request <- function(google_slides_request = NULL, shape_type = NULL, page_element_property = NULL, object_id = NULL){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }
  # Input Validation
  assert_that(is.character(shape_type))

  create_shape_request <- list(createShape = list(elementProperties = page_element_property$to_list(),
                                               shapeType = shapeType))
  google_slides_request$add_request(create_shape_request)
  return(google_slides_request)

}


#' Add a replace all text request
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param replace_text A character vector of text that would replace the ones in the text parameter.
#' The order of the replaceText matters
#' @param text A character vector of text that would replaced by the ones in the replaceText parameter.
#' The order of the text matters
#' @param match_case A boolean that takes in only TRUE or FALSE only. This would be applied across all
#' requests
#' @importFrom assertthat assert_that
#' @export
add_replace_all_text_request <- function(google_slides_request = NULL, replace_text=NULL, text=NULL, match_case=TRUE){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }
  # Input Validation
  assert_that(is.character(replace_text))
  assert_that(is.character(text))
  assert_that(is.logical(match_case))

  replace_all_text_list <- list(replaceAllText = list(replaceText = replace_text,
                                                      containsText = list(text = text, matchCase = match_case)))
  google_slides_request$add_request(replace_all_text_list)
  return(google_slides_request)
}


#' Add an insert text request
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param object_id A character vector of objects to insert text into. You can only insert text in
#' tables and shapes
#' @param row_index A numeric vector of row to insert the text into
#' @param column_index A numeric vector of column to insert the text into
#' @param text A character vector of text which is to be inserted into the shape or table
#' @param insertion_index A numeric vector which indicate the starting point of how the text
#' is to be inserted
#' @export
add_insert_text_request <- function(google_slides_request = NULL, object_id=NULL,
                              row_index=NULL, column_index=NULL,
                              text=NULL, insertion_index=NULL){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }
  insert_text_request <- list(insertText = list(objectId = object_id, text = text))
  if(!is.null(rowIndex) & !is.null(columnIndex)){
    insert_text_request[["insertText"]][["cellLocation"]] = list()
    insert_text_request[["insertText"]][["cellLocation"]][["rowIndex"]] <- row_index
    insert_text_request[["insertText"]][["cellLocation"]][["columnIndex"]] <- column_index
  }
  if(!is.null(insertionIndex)){
    insert_text_request[["insertText"]][["insertionIndex"]] <- insertion_index
  }
  google_slides_request$add_request(insert_text_request)
  return(google_slides_request)
}


#' Add an insert table row request
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param table_object_id The table to insert rows into.
#' @param row_index The 0-based row index.
#' @param column_index The 0-based column index.
#' @param insert_below Whether to insert new rows below the reference cell location. If True, cells will
#' be inserted below cell reference. If False, cells will be inserted above cell reference.
#' @param number The number of rows to be inserted. Maximum 20 per request.
#' @importFrom assertthat assert_that is.number
#' @export
add_insert_table_rows_request <- function(google_slides_request = NULL, table_object_id,
                                    row_index, column_index, insert_below = TRUE,
                                    number){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }
  # Check input parameters
  assert_that(is.character(table_object_id))
  assert_that(is.number(row_index))
  assert_that(is.number(column_index))
  assert_that(is.logical(insert_below))
  assert_that(is.number(number))
  insert_table_rows_request <- list(tableObjectId = table_object_id,
                                    insertBelow = insert_below,
                                    number = number)
  insert_table_rows_request[['cellLocation']] <- list()
  insert_table_rows_request[['cellLocation']][['rowIndex']]  <- row_index
  insert_table_rows_request[['cellLocation']][['columnIndex']] <- column_index
  google_slides_request$add_request(insert_table_rows_request)
  return(google_slides_request)
}


#' Add a delete text request
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param object_id A character vector of objects to insert text into. You can only insert text in
#' tables and shapes
#' @param row_index A numeric vector of row to insert the text into
#' @param column_index A numeric vector of column to insert the text into
#' @param start_index The optional zero-based index of the beginning of the collection.
#' Required for SPECIFIC_RANGE and FROM_START_INDEX ranges.
#' @param end_index The optional zero-based index of the end of the collection.
#' Required for SPECIFIC_RANGE delete mode.
#' @param type The type of range. Can be the following RANGE_TYPE_UNSPECIFIED, FIXED_RANGE,
#' FROM_START_INDEX, ALL
#' @export
add_delete_text_request <- function(google_slides_request = NULL, object_id = NULL,
                              row_index = NULL, column_index = NULL,
                              start_index = NULL, end_index = NULL,
                              type = "ALL"){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }
  delete_text_request <- list(deleteText = list(objectId = object_id))
  if(!is.null(row_index) & !is.null(column_index)){
    delete_text_request[["deleteText"]][["cellLocation"]] <- list()
    delete_text_request[["deleteText"]][["cellLocation"]][["rowIndex"]] <- row_index
    delete_text_request[["deleteText"]][["cellLocation"]][["columnIndex"]] <- column_index
  }
  delete_text_request[["deleteText"]][["textRange"]][["type"]] <- list()
  delete_text_request[["deleteText"]][["textRange"]][["type"]] <- type
  if(!is.null(start_index)){
    delete_text_request[["deleteText"]][["textRange"]][["startIndex"]] <- start_index
    delete_text_request[["deleteText"]][["textRange"]][["endIndex"]] <- end_index
  }
  google_slides_request$add_request(insert_text_request)
  return(google_slides_request)
}


#' Add a delete object request
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param objectId A character vector of object ids that is to be deleted from the slides
#' @export
add_delete_object_request <- function(google_slides_request = NULL, object_id=NULL){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }
  delete_object_request <- list(deleteObject = list(objectId = object_id))
  google_slides_request$add_request(delete_object_request)
  return(google_slides_request)
}

#' Add an update slides position request
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param slide_object_ids A character vector of slide ids
#' @param insertion_index Numeric Vector. This is where the slides selected in
#' slideobjectids parameter is inserted into. The slides would be inserted based on before the arrangement
#' before the move.
#' @export
add_update_slides_position_request <- function(google_slides_request = NULL, slide_object_ids=NULL,
                                         insertion_index=NULL){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }
  update_slides_postion_request <- list(updateSlidesPosition = list(slideObjectIds = list(slide_object_ids),
                                     insertionIndex=insertion_index))
  google_slides_request$add_request(update_slides_postion_request)
  return(google_slides_request)
}

#' Add a create table request
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param page_element_property A list that contains a page element property. The page element is to be
#' generated by the page_element_property function in this package.
#' @param rows A numeric vector with the row index of the data to be filled in the table. Only for tables
#' @param columns A numeric vector with the column index of the data to be filled in the table. Only for tables
#' @param objectId (Optional) A character vector to name the object created instead of leaving it to Google
#' @export
add_create_table_request <- function(google_slides_request = NULL, page_element_property = NULL,
                                     rows = NULL, columns = NULL, object_id = NULL){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }
  # Validating inputs
  assert_that(is.google_slide_request(google_slides_request))
  assert_that(is.page_element_property(page_element_property))
  assert_that(is.numeric(rows))
  assert_that(is.numeric(columns))
  assert_that(is.character(object_id) | is.null(object_id))

  create_table_request <- list(createTable = list(elementProperties = page_element_property$to_list(),
                                               rows = rows,
                                               columns = columns))
  google_slides_request$add_request(create_table_request)
  return(google_slides_request)
}

#' Add a create image request
#' @param google_slides_request A Google Slides Request object which is used to manage requests to the API
#' @param url A character vector container an image url that is to be used to add image to the slides
#' @param pageElementProperty A list that contains a page element property. The page element is to be
#' generated by the page_element_property function in this package.
#' @param objectId (Optional) A character vector to name the object created instead of leaving it to Google
#' @export
add_create_image_request <- function(google_slides_request = NULL, url=NULL,
                               page_element_property=NULL, object_id=NULL){
  if(is.null(google_slides_request)){
    google_slides_request <- google_slide_request_container$new()
  }
  # Validating inputs
  assert_that(is.google_slide_request(google_slides_request))
  assert_that(is.character(url))
  assert_that(is.page_element_property(page_element_property))
  assert_that(is.character(object_id) | is.null(object_id))

  # Check if url contains
  if (!grepl("http", url, fixed = TRUE)){
    drive_url <- "https://www.googleapis.com/drive/v3/files/<file_id>?alt=media&access_token=<access_token>"
    access_token <- get_token()$credentials$access_token
    drive_url <- gsub("<file_id>", url, drive_url, fixed = TRUE)
    drive_url <- gsub("<access_token>", access_token, drive_url, fixed = TRUE)
    url <- drive_url
  }

  create_image_request <- list(createImage = list(elementProperties = page_element_property$to_list(),
                                               url = url))
  google_slides_request$add_request(create_image_request)
  return(google_slides_request)
}
